# 服务配置
server:
  port: 8888

# spring 相关配置
spring:
  profiles:
    active: @spring.active@   # mvn clean package -P test 命令时， @profiles.active@ 会替换成 test

# 日志配置
logging:
  level:
    root: info
    com.blog: debug

# mybatisPlus 相关配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
